Maze generator
kysect/MazeGenerator pull request #1
Opened 2022-09-26 14:10 UTC by Step1532

2022-09-26 14:23 UTC, FrediKats requested changes
Пару замечаний для начала.

2022-09-26 14:23 UTC, FrediKats commented on .gitignore
> +/Source/Kysect.MazeGenerator.Console/obj
Возьми дефолтный студийный игнор - https://github.com/kysect/Main/pull/42.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/IMazeGenerator.cs
> +    public byte[][] Generate(int size);
Зачем public? И почему на это анализатор не ругается =_=

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +#pragma warning restore CA1028 // Enum Storage should be Int32
А будет таска на то, чтобы заменить на int?

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +    East = 0x8
А дирекшен может быть сразу в несколько направлений? Почему это флаги?

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +        });
Почему это лист ил массивов, а не пар? Тут же всегда два элемента? Лучше уже сделать какую-то стркутуру Point. Оно ещё и по аллокациям лучше будет!

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +            short index = (short)ChooseIndex((ushort)cells.Count);
Нужно что-то сделать с этой кучей кастов. Много вопросов вызывает.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +        return index;
Выглядит как Math.Max(max - 1, 0);

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +        var directions = (Direction[])Enum.GetValues(typeof(Direction));
В нет6 есть метод у енама GetValues, емнип.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +    }
Давай вынесем это в отдельный класс. Это дженерик вещь, которая не связана с генерацией.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +        };
Вот тут аналогично. Я бы ожидал, что тут будет структура Point или подобное. А это метод выглядит как ConvertDirectionToPoint и можем быть сделан ввиде эксетнеш метода над Direction. Тоже не связан непосредственно с логикой генерации.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                short ny = (short)(y + move[1]);
Сделать у структуры Point оператор + и туда вынести это.

2022-09-26 14:23 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +    }
Тоже унести в экстеншен метод над Direction.

2022-09-26 16:59 UTC, FrediKats commented
@Bibletoon @s4xack @annchous @hrrrrustic  есть желание посмотреть?)

Это либа для https://github.com/kysect/Main/pull/43 (можно тоже посомтреть!).

2022-09-26 18:08 UTC, annchous requested changes, later dismissed

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +    public static Direction OppositeDirection(this Direction direction)
Кажется, тут не хватает Get. GetOppositeDirection или другой глагол на твой вкус.

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +    public static Cell DirectionToDelta(this Direction facingDirection)
Тоже не хватает глагола в названии метода. Типа TransformDirectionTo... или что-то такое.

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +    private readonly Random _rnd;
Буквы можно не экономить и написать _random )

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +    private void GenerateTWMaze_GrowingTree(byte[][] maze)
Это точно нужно переименовать, чтобы, как минимум, убрать нижнее подчёркивание из названия метода. Это не по кодстайлу.

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                if (pos.X >= 0 && pos.Y >= 0 && pos.X < maze.Length && pos.Y < maze[0].Length && maze[pos.X][pos.Y] == 0)
Условие можно вытащить в отдельный приватный метод и разбить на более простые конструкции по типу:

if (pos.X < 0)
    return false;

и так далее

2022-09-26 18:08 UTC, annchous commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +            throw new ArgumentException("");
Кажется, тут должна была быть сообщенька, но её нет )

2022-09-26 18:51 UTC, hrrrrustic commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(direction), direction, null)
А вот на фшарпе бы...

2022-09-26 18:51 UTC, hrrrrustic commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            (directions[r], directions[i]) = (directions[i], directions[r]);
Вообще не понял, что происходит

2022-09-26 18:51 UTC, hrrrrustic commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                lineToBlock[(2 * x) + 2][(2 * y) + 2] = 1;
Ну это анрил прочитать, выглядит как какая-то магия

2022-09-26 18:58 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(direction), direction, null)
хых

> А вот на фшарпе бы...

хых

2022-09-26 18:58 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            (directions[r], directions[i]) = (directions[i], directions[r]);
свап

2022-09-26 18:58 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                lineToBlock[(2 * x) + 2][(2 * y) + 2] = 1;
так и есть

2022-09-26 19:11 UTC, hrrrrustic commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            (directions[r], directions[i]) = (directions[i], directions[r]);
Свап чего? Что такое r?

2022-09-26 19:19 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Direction.cs
> +            (directions[r], directions[i]) = (directions[i], directions[r]);
r - рандомный индекс из "непройденного" массива

Проходимся по массиву, на каждой итерации выбираем рандомный элемент из оставшегося массива. Меняем местами значения по текущему и рандомному индексу. Получаем на выходе рандомный массив

2022-09-27 00:58 UTC, hrrrrustic commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +            throw new ArgumentException($"{nameof(size)} must be greater than 1");
А?

2022-09-27 04:24 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                lineToBlock[(2 * x) + 2][(2 * y) + 2] = 1;
С этим было бы неплохо что-то сделать)

2022-09-27 07:53 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +                lineToBlock[(2 * x) + 2][(2 * y) + 2] = 1;
пока не смогу. Может потом свою генерацию напишу

2022-09-28 15:17 UTC, FrediKats approved these changes
Я думаю, что на первую иттерацию ок. Потом можно будет допиливать по необходимости.

2022-09-28 15:17 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/Cell.cs
> +public struct Cell
Я бы над неймингом подумал. А то как-то не вяжется. У тебя это и координаты, и вектор направления. А название Cell.

2022-09-28 16:32 UTC, merged