feat: generating exit
kysect/MazeGenerator pull request #2
Opened 2022-09-30 16:09 UTC by Step1532

2022-09-30 16:32 UTC, FrediKats requested changes
Вообще, я думал, что логика сведётся к тому, что мы просто одну стену удалим 🤔

2022-09-30 16:32 UTC, FrediKats commented on Source/Kysect.MazeGenerator.Console/Program.cs
> +IMazeGenerator generator = new GrowingTreeGenerator((int)DateTime.Now.Ticks);
Давай добавим конструктор с дефолтными значением и будем брать рандом инт?

2022-09-30 16:32 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
>              throw new ArgumentException($"{nameof(size)} must be greater than 1");
Показания не сходятся!

2022-09-30 16:32 UTC, FrediKats commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
> +        map[exitPosition.X][exitPosition.Y] = Cells.Empty;
Тут есть две проблемы:

1. Смешиваются конептуальные вещи и детали
2. Не очень очевидная логика. Не очень понятно, что за дельта, например

Давай начнём с того, что будем инкапсулировать детали:

- Вместо того, чтобы генерить массив и брать первый элемент, давай сделаем ещё один метод, который вернём рандомный элемент
- (int)((_random.NextDouble() * (map.GetLength(0) - 1)) + 1); - очень странная конструкция, ещё и сетиться в переменную с плохим неймингом. У рандома же есть метод получения инта и даже в рендже заданном. Давай его заюзаем + нейминг подправим

2022-09-30 18:31 UTC, Step1532 commented on Source/Kysect.MazeGenerator/MazeGenerators/GrowingTree/GrowingTreeGenerator.cs
>              throw new ArgumentException($"{nameof(size)} must be greater than 1");
если size  = 1 срабатывает ексепшн
если 2 - все ок
Показания сходятся.

Но соглашусь, _текст по дебильному написан_

2022-10-01 13:01 UTC, FrediKats approved these changes

2022-10-01 17:11 UTC, FrediKats approved these changes

2022-10-06 04:43 UTC, FrediKats commented
@Step1532  merge?

2022-10-06 04:45 UTC, merged